### ISSUE TITLE
UMD Video won't dump

### ISSUE THREAD

**Issue by soxhi8** [saramibreak/UmdImageCreator#1]
I'm trying to dump an UMD Video-disc, but the disc won't start spinning. PSP-2004 FW 6.61 C-2, ~ 3 Gigs free on memory stick.

Log:

pspUmdTypes: 0x20 (VIDEO)

L0 length: 442560 (0x6c0c0)
L1 length: 434944 (0x6a300)
---------------------------------
Total: 877504 (0xd63c0)
FileSize: 1797128192 (0x6b1e0000)

0x01F20014 is unknown: 05 80 00 32
0x01F200A0 is unknown: 20
Wait until UMD is ready => NG: result=0x800201A8
Cannot open UMD_DATA.BIN: result=0x80010013

Any idea what could be causing this?

**Comment by saramibreak** [comment]
> If you use EBOOT.PBP, move GAME and press circle on UmdImageCreator
If you use UmdImageCreator.prx, press note

Perhaps if you use prx, it'll start spinning.
But ripping speed of this app is very slow. If you have other app, I recommend it.

**Comment by soxhi8** [comment]
> > If you use EBOOT.PBP, move GAME and press circle on UmdImageCreator
> > If you use UmdImageCreator.prx, press note
> 
> Perhaps if you use prx, it'll start spinning.
> But ripping speed of this app is very slow. If you have other app, I recommend it.

Didn't change with the prx. The only that changed is that the Video automatically launched after closing the UIC. Thanks for the reply though!
But dumping via USB UMD Drive worked.
