### ISSUE TITLE
Sanitize filenames

### ISSUE THREAD

**Issue by eubrunosilva** [saramibreak/UmdImageCreator#5]
I have one UMD that i'm trying to dump and it gives an error in writing files because it has a ':' in volume name (not sure if you get this label from from volume name or other).

its possible to sanitize the filenames (logs and iso)?
Thanks

**Comment by saramibreak** [comment]
Replaced ':' to '_'
[UmdImageCreator_test.zip](https://github.com/saramibreak/UmdImageCreator/files/8113320/UmdImageCreator_test.zip)

**Comment by eubrunosilva** [comment]
Hi
it works :)
Thanks
