### ISSUE TITLE
UMD Dump not starting if iso folder is missing

### ISSUE THREAD

**Issue by Razorbacktrack** [saramibreak/UmdImageCreator#6]
You have to manually create the folder to successfully dump the UMD.

Tested with a PSP 1000 with ARK4 CFW

**Comment by saramibreak** [comment]
added creating iso directory automatically
[UmdImageCreator_test.zip](https://github.com/saramibreak/UmdImageCreator/files/13804892/UmdImageCreator_test.zip)

**Comment by Razorbacktrack** [comment]
> added creating iso directory automatically [UmdImageCreator_test.zip](https://github.com/saramibreak/UmdImageCreator/files/13804892/UmdImageCreator_test.zip)

I can confirm that it's working now (tested using the app and the plugin).
Thank you
