### ISSUE TITLE
crash with `Directory Record is over 400`

### ISSUE THREAD

**Issue by f-fix** [saramibreak/UmdImageCreator#7]
UmdImageCreator crashes with `Directory Record is over 400`, then powers off the PSP. Seen so far with NPJH-50473, ULUS-10051 and ULUS-10551 

**edit:** this was seen using the version downloaded from https://github.com/saramibreak/UmdImageCreator/releases/tag/v1.6 on a PSP-3001 running system 6.61 PRO-C∞

**Comment by f-fix** [comment]
i think the limit is defined here: https://github.com/saramibreak/UmdImageCreator/blob/master/UmdImageCreator/forwardDeclaration.h#L21
```c++
#define PATH_TABLE_RECORD_SIZE	(400)
```
... however i don't know why 400 was chosen, nor whether it is ok to simply increase it

**Comment by saramibreak** [comment]
IIRC, I think the value was selected because memory could not be allocated.
I will consider if there are other solutions in the near future.

**Comment by saramibreak** [comment]
> IIRC, I think the value was selected because memory could not be allocated.
I will consider if there are other solutions in the near future.

Apparently, I was mistaken. 
[UmdImageCreator_test.zip](https://github.com/saramibreak/UmdImageCreator/files/14789579/UmdImageCreator_test.zip)
- changed `PATH_TABLE_RECORD_SIZE` to 4000

**Comment by f-fix** [comment]
> > IIRC, I think the value was selected because memory could not be allocated.
> > I will consider if there are other solutions in the near future.
> 
> Apparently, I was mistaken. [UmdImageCreator_test.zip](https://github.com/saramibreak/UmdImageCreator/files/14789579/UmdImageCreator_test.zip)
> 
> * changed `PATH_TABLE_RECORD_SIZE` to 4000
<img src="https://github.com/saramibreak/UmdImageCreator/assets/164929254/6e5945a3-9133-4e10-ad2d-9b8026bcb700" width="200"  align="right" />
This build is looking promising! Apparently one of those discs (ULUS-10551) has 494 Directory Records and it seems like it's making progress now...

**Comment by f-fix** [comment]
> > IIRC, I think the value was selected because memory could not be allocated.
> > I will consider if there are other solutions in the near future.
> 
> Apparently, I was mistaken. [UmdImageCreator_test.zip](https://github.com/saramibreak/UmdImageCreator/files/14789579/UmdImageCreator_test.zip)
> 
> * changed `PATH_TABLE_RECORD_SIZE` to 4000

Thanks! The test build got working images from ULUS-10051 and ULUS-10551 that match PSP Filer images and also match file hashes reported previously by other people at redump.org

Unfortunately NPJH-50473 is crashing at a later point now, but I think it's no longer this issue since it reads the 438 DirectoryRecords first before it suddenly exits after reporting shortage
![IMG_20240329_112318_715](https://github.com/saramibreak/UmdImageCreator/assets/164929254/64575d24-0c52-4a70-86c6-fd5f872bd2f0)

In the released build I used previously for discs with fewer than 400 directory records sometimes shortage would be declared but dump would proceed anyhow, but with this build it is simply exiting at that point without creating a .iso file

I was able to get it to dump with the test build be deleting another file so that the free space computation would wrap around, but it woud be better to not require these silly workarounds.

I should add: there is actually much more space available, memory stick is a dual-slot TF adapter with two SD cards (decimal 128 GB and decimal 8 GB) summing to around 126 GB binary, and over 60GB are free still.

**Comment by f-fix** [comment]
I was able to get redump-matching images for all three discs using the test binary, however it seems to have a regression concerning exiting on spurious computed shortage

**Comment by saramibreak** [comment]
> memory stick is a dual-slot TF adapter with two SD cards (decimal 128 GB and decimal 8 GB) summing to around 126 GB binary, and over 60GB are free still.

It seems `Max (2636447744)` and `Free (672399360)` of the `MemoryStick size` overflow.
Uploaded.
[UmdImageCreator_test.zip](https://github.com/saramibreak/UmdImageCreator/files/14809966/UmdImageCreator_test.zip)

**Comment by f-fix** [comment]
> > memory stick is a dual-slot TF adapter with two SD cards (decimal 128 GB and decimal 8 GB) summing to around 126 GB binary, and over 60GB are free still.
> 
> It seems `Max (2636447744)` and `Free (672399360)` of the `MemoryStick size` overflow. Uploaded. [UmdImageCreator_test.zip](https://github.com/saramibreak/UmdImageCreator/files/14809966/UmdImageCreator_test.zip)

thanks! i will try this one the next time my space computation reaches the overflow conditions

**Comment by f-fix** [comment]
> > memory stick is a dual-slot TF adapter with two SD cards (decimal 128 GB and decimal 8 GB) summing to around 126 GB binary, and over 60GB are free still.
> 
> It seems `Max (2636447744)` and `Free (672399360)` of the `MemoryStick size` overflow. Uploaded. [UmdImageCreator_test.zip](https://github.com/saramibreak/UmdImageCreator/files/14809966/UmdImageCreator_test.zip)

Unfortunately this build still crashes with a shortage. Under same false shortage conditions release 20231201 still dumps just fine though

Build 20231201 working 
![17135652445745046062908255451871](https://github.com/saramibreak/UmdImageCreator/assets/164929254/3df4ce1d-7e19-4967-888a-e43c80e07af2)

Test build crashes right after this message
![IMG_20240419_151428_980](https://github.com/saramibreak/UmdImageCreator/assets/164929254/8b9393de-0aa4-4556-9f37-b88fb1da05bf)

Free space reported by system (it matches what I see from Windows too)
![IMG_20240419_151456_097](https://github.com/saramibreak/UmdImageCreator/assets/164929254/b4ff0735-1568-48ed-a552-4601288ba5c6)

**Comment by saramibreak** [comment]
fixed again.
[UmdImageCreator_test.zip](https://github.com/saramibreak/UmdImageCreator/files/15052531/UmdImageCreator_test.zip)

**Comment by Still34** [comment]
Tested - works with NPJH-50473

**Comment by saramibreak** [comment]
@Still34 
Thanks.
